[package]
name = "yu"
version = "0.1.0"
edition = "2021"

[dependencies]
fluent = "0.16.1"
fluent-resmgr = "0.0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
unic-langid = { version = "0.9.5", features = ["macros"] }
